* ROADMAP Coralpetro

** Instalar PyAudio
   - para poder manejar archivos y buffers de audio

   - con pip3 install pyaudio me dice que le falta una lib portaudio.h

   - lo instalo directo de la pagina de portaudio, uso el paquete ponce para x86

** Instalar PyAudio en Raspbian
   You can compile PortAudio directly on the Raspberry Pi.
   PortAudio uses ALSA. So you will need to install the ALSA developer library
   $ sudo apt-get install libasound-dev

   I recommend using the nightly snapshot of PortAudio V19 from http://www.portaudio.com/download.html

   Then compile PortAudio and the examples.
   $ cd portaudio
   $ ./configure
   $ make
   $ sudo make install

*** Script Test
    - hago un test de dispositivos 

*** Scripts de prueba con wav
    https://riptutorial.com/python/topic/10627/pyaudio

*** Wave Tutorial
    https://nbviewer.jupyter.org/github/mgeier/python-audio/blob/master/audio-files/audio-files-with-wave.ipynb

*** Para grabar audio con el mic
    https://realpython.com/playing-and-recording-sound-python/

*** Intro PyAudio
    https://slides.com/jeancruypenynck/introduction-to-pyaudio/embed#/

** Download audio or video from Youtube
*** Como lo uso, si quiero solo el audio
    youtube-dl --extract-audio --audio-format wav https://www.youtube.com/watch?v=kiMqDjazJwk

*** youtube-dl
    - Lo baje desde slackbuilds.org

*** Necesito ffmpeg para convertir formatos de audio
    - si quiero bajar y convertir con youtube-dl usa ffmpeg
    - Lo bajo con slpkg, tarda bastante porque lo compila como lib

*** Para escuchar o info del wav con SOX
    - sox si esta instalado lo puedo llamar directamente con play
      que es un wrapper
    $ play 2minutos.wav

    - info del header del archivo la puedo conseguir con soxi
    $ soxi output.wav

*** Para escuchar el wav con ffmpeg
    - con ffmpeg instalado tengo el wrapper ffplay
    $ ffplay 2minutos.wav

** Uso de wave lib-std de python
   - docu original
     https://docs.python.org/3/library/wave.html
     
   - buenos ejemplos de uso
     http://blog.acipo.com/wave-generation-in-python/

   - RIFF & WAV headers
     http://www-mmsp.ece.mcgill.ca/Documents/AudioFormats/WAVE/WAVE.html

** Tomar audio por el mic

* Things to be Done
** DONE Manejar archivos y buffers de audio
   CLOSED: [2020-02-04 Tue 08:59]
** DONE Escuchar por mic grabar buffer o archivo
   CLOSED: [2020-02-04 Tue 09:00]
** TODO Enviar audio al control <audio> html
** TODO Enviar mic al control <audio>
** Armar un pipe o queue para compartir mic
*** Para varias instancias de flask necesito compartir los mismos audio samples
    El mismo origen de datos entre las instancias de flask

** Pagina de inicio y logging
   https://pythonspot.com/login-authentication-with-flask/

   https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-v-user-logins   

   https://flask-login.readthedocs.io/en/latest/

   https://stackoverflow.com/questions/54992412/flask-login-usermixin-class-with-a-mongodb


** Pagina principal con control <audio> y usuarios loggeados
** Pagina armar nuevo usuario
** Base de datos usuarios y log
** Graba archivos de audio?
** Mejorar calidad del mic, se escucha mucho ruido de fondo

   
* MongoDB Pymongo
  https://api.mongodb.com/python/current/tutorial.html#tutorial

  https://stackoverflow.com/questions/41514896/how-can-i-use-mongodb-with-flask


* Varios Links de Flask
** flask werkzeug multiple connections
   https://stackoverflow.com/questions/14814201/can-i-serve-multiple-clients-using-just-flask-app-run-as-standalone

   https://stackoverflow.com/questions/43180733/handle-multiple-connections-in-flask-api

   app.run(host='0.0.0.0', debug=True, threaded=True)
** socket.io
   https://socket.io/

   https://www.npmjs.com/package/socket.io-stream

   https://nodejs.org/api/stream.html

   https://github.com/substack/stream-handbook

   https://stackoverflow.com/questions/28394340/how-to-play-a-sound-from-a-socket-io-event


** audio control and stream audio html5
   http://www.diva-portal.org/smash/get/diva2:1023478/FULLTEXT02.pdf

   https://gabrieltanner.org/blog/webrtc-video-broadcast

   https://buildthings.wordpress.com/remote-ham-radio-base-station-voip-web-auio-api-html5-audio-node-js-server-raspberry-pi/

** por el reproductor
   https://apiko.com/blog/audio-file-streaming-in-js/

** socket.io and audio control
   https://medium.com/@saurssaurav33/how-to-make-a-browser-walkie-talkie-using-node-js-and-socket-io-ae024bb9b378

* Flask multiple pages multiple stylesheets
** Paginas
   - Dentro de /template
   - en el template del html, dentro del header, hacer referencia al style que uso

   <html>
   <head>
   <link rel= "stylesheet" type= "text/css" href= "../styles/mainpage.css">
   </head>
   <body>
   <!-- content --> 

   - tipicamente para que jinja funcione mejor
     <link rel= "stylesheet" type= "text/css" href= "{{ url_for('static',filename='mainpage.css') }}">

** Stylesheets
   - Dentro de /static pondo los .css con los nombres de los links de las paginas

** input overflow (veo el defaultSampleRate)
   >>> import pyaudio
   >>> audio_dev = pyaudio.PyAudio()
   >>> audio_dev.get_device_info_by_index(0)['defaultSampleRate']
   >>> 44100.0

** cada tanto se corta el audio, cada 10min aprox
   - es un tema con pyaudio
   cuando leo el chunck con read, le paso un flag para que no me salte el error

   currChunk = audio_stream.read(CHUNK, exception_on_overflow=True)

* Flask socket io
** Instalacion
   pip3 install flask-socketio

** Manual
   https://flask-socketio.readthedocs.io/en/latest/

** Funcionamiento con Audio Control
   After lots research and tinkering I finally found the solution.
   Basically it came down to serving pyaudio.paFloat32 audio data through 
   WebSockets using Flask's SocketIO implementation and receiving/playing
   the data in JavaScript using HTML5's AudioContext.

   As this is requires quite some code, I think it would not be a good 
   idea to post it all here. Instead, feel free to check out the project 
   I'm using it in: simpleCam
   https://github.com/paranerd/simplecam

   The relevant code is in: 
   - noise_detector.py (recording) 
   - server.py (WebSocket transfer) 
   - static/js/player.js (receiving/playing)

   Thanks everyone for the support!
   Stream audio from pyaudio with Flask to HTML5
   https://stackoverflow.com/questions/47106364/stream-audio-from-pyaudio-with-flask-to-html5

** Conectar un Button HTML con JavaScript
   https://stackoverflow.com/questions/1947263/using-an-html-button-to-call-a-javascript-function


* 27-06-2020 usando flask-io/app_io.py
** Logging muy importante
   - que el que escucha no pueda cambiar canales

*** O por lo menos emitir desde IO quien hizo el ultimo cambio
** Mover canales con botones
** Seguir probando buffers Play/Pause

* getUserMedia()
  - no funciona en los browser sino es https la pagina, o no esta en localhost

** para firefox about:config
   buscar insecure
   media.devices.insecure.enabled -> true
   media.getusermedia.insecure.enables -> true

* Agregar un self signed certificate para poder correr https
  - https://flaviocopes.com/express-https-self-signed-certificate/

** con OpenSSL
   openssl req -nodes -new -x509 -keyout server.key -out server.cert

    

* Instalacion 28-10-2020
** Cambiar IP del server por conflictos con la red
*** En RPI
    - en /etc/dhcpcd.conf
    - cambiar ip y gw
      ip 192.168.1.103
      router 192.186.1.6
      dns 192.168.1.6 8.8.8.8

*** Usuario
    maximiliano
    su pi

** Frenar servicio
   $ sudo systemctl stop clock.service

* DuckDNS
Creamos el fichero
 nano duck.sh
Y copiamos el texto que tienes en la página web con el token de tu nombre de dominio

echo url="https://www.duckdns.org/update?domains=vhfpilotage&token=0f8b5f5e-ef01-4127-aca6-b38c8005c6f5&ip=" | curl -k -o ~/duckdns/duck.log -K -

Damos permisos de ejecución al fichero
 chmod 700 duck.sh

Editamos el servicio cron para hacer que el fichero se ejecute cada 5 minutos
 crontab -e

Y copiamos el siguiente texto
*/5 * * * * ~/duckdns/duck.sh >/dev/null 2>&1

Para guardar el fichero pulsamos CTRL+x

Probamos que el script funciona
 ./duck.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     2    0     2    0     0      2      0 --:--:-- --:--:-- --:--:--     2

Esto creará un fichero llamado duck.log, el cual tendrá dos valores OK, si todo ha ido bien o bad KO si ha habido algún problema.
cat duck.log
OK
A partir de ahora., cada vez que se acceda al nombre de dominio vhfpilotage.duckdns.org estaré accediendo al servidor, concretamente al puerto 80 (puerto por defecto)

* Inspeccionar codigo Node.JS
** con Vivaldi
   - ejecuto el script
     $ node --inspect index.js slackware

   - en vivaldi busco para abrir la consola, deberia encontrar el proceso index.js corriendo con su PID
     vivaldi://inspect

* Fuerzo GC
** Agrego una funcion que la voy a llamar con un timer de 2horas
function forceGC()
   if (global.gc) {
      global.gc();
   } else {
      console.warn('No GC hook! Start your program as `node --expose-gc file.js`.');
   }
}

** Debo hacer correr el programa con --expose-gc

* DuckDNS specific coralpetro config
** duckdns account
   [[./duck_account.org][archivo de la cuenta]]
